-- Migration 022: corrige telefones de clientes importados do vm2025 sem DDD.
-- O sistema legado guardava telefone/celular sem DDD — o DDD vinha implícito pela
-- cidade do cliente (tabela `cidade` do legado). A importação (importar-vm2025.ts)
-- não compôs o DDD no telefone, deixando a maioria dos registros sem DDD.
--
-- Heurística de correção (baseada em 2 pistas do usuário):
--   1. DDD vem da cidade/UF do cliente, via tabela de referência abaixo (extraída
--      do dump legado db/legado/migrado_de_vm2025.sql, tabela `cidade`).
--   2. Telefone só recebe DDD se ainda não tiver um: 8 dígitos = fixo (formato
--      "XXXX-XXXX"), 9 dígitos = celular (formato "XXXXX-XXXX"). Números com 10+
--      dígitos já têm DDD embutido e são apenas reformatados para "(XX) ...".
--
-- IMPORTANTE: cidade->DDD é só uma muleta para corrigir o dado legado, não uma
-- regra de negócio do vm2026 — um cliente pode morar numa cidade e ter telefone
-- com DDD de outra. Por isso a tabela de referência é temporária: criada, usada
-- nos UPDATEs abaixo e descartada (DROP) ao final desta mesma migration. Daqui
-- para frente, telefone sempre é digitado completo (com DDD) pelo usuário.

CREATE TABLE IF NOT EXISTS cidades_ddd_referencia (
  cidade VARCHAR(100) NOT NULL,
  uf CHAR(2) NOT NULL,
  ddd CHAR(2) NOT NULL,
  PRIMARY KEY (cidade, uf)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO cidades_ddd_referencia (cidade, uf, ddd) VALUES
('Xinguara','PA','94'),
('MORENO','PE','81'),
('CONCEIÇÃO DO MATO DENTRO','MG','31'),
('SÃO JOSÉ DO RIO PARDO','SP','19'),
('ALEGRE','ES','28'),
('ALENQUER','PA','93'),
('ALFENAS','MG','35'),
('ALAGOINHAS','BA','75'),
('ALTA FLORESTA','MT','66'),
('ALTAMIRA','PA','93'),
('ALTO  PARANA','PR','44'),
('ALTO  PIQUIRI','PR','44'),
('ALTONIA','PR','44'),
('AMAMBAI','MS','67'),
('AMARANTE DO MARANHAO','MA','99'),
('AMERICANA','SP','19'),
('ANAPOLIS','GO','62'),
('ANGRA DOS REIS','RJ','24'),
('APARECIDA','SP','12'),
('APARECIDA DE GOIANIA','GO','62'),
('APARECIDA DO NORTE','SP','12'),
('APUCARANA','PR','43'),
('AQUIDAUANA','MS','67'),
('AQUIRAZ','CE','85'),
('ARACAJU','SE','79'),
('ARACATUBA','SP','18'),
('ARACRUZ','ES','27'),
('ARAGUAIA','PA','91'),
('ARAGUAINA','TO','63'),
('ARAPIRACA','AL','82'),
('ARAPUTANGA','MT','65'),
('ARARANGUA','SC','48'),
('ARARAQUARA','SP','16'),
('ARARAS','SP','19'),
('ARARIPINA','PE','87'),
('ARARUAMA','RJ','22'),
('ARAXA','MG','34'),
('ARCOVERDE','PE','87'),
('AREAL','RJ','24'),
('ARIPUANÃ','MT','66'),
('ARIQUEMES','RO','69'),
('ASSIS','SP','18'),
('ATALAIA DO NORTE','AM','97'),
('AYMORES','MG','33'),
('BACABAL','MA','99'),
('BAGE','RS','53'),
('BALNEARIO CAMBORIU','SC','47'),
('BALSAS','MA','99'),
('BANANEIRAS','PB','83'),
('BARAO  DE GRAJAU','MA','99'),
('BARBACENA','MG','32'),
('BARRA DO BUGRE','MT','65'),
('BARRA DO CORDA','MA','99'),
('BARRA DO GARCAS','MT','66'),
('BARRA MANSA','RJ','24'),
('BARREIRA','BA','73'),
('BARREIRAS','BA','77'),
('BARRETOS','SP','17'),
('BARUERI','SP','11'),
('BATURITE','CE','85'),
('BAURU','SP','14'),
('BELA VISTA','MS','67'),
('BELEM','PA','91'),
('BELO HORIZONTE','MG','31'),
('BELO JARDIM','PE','81'),
('BETIM','MG','31'),
('BLUMENAU','SC','47'),
('BOA  VIAGEM','CE','88'),
('BOA VISTA','RR','95'),
('BOM JESUS DA LAPA','BA','77'),
('BOM JESUS DE ITABAPOANA','RJ','22'),
('BOTUCATU','SP','14'),
('BRAGANCA','PA','91'),
('BRAGANCA PAULISTA','SP','11'),
('BRASILEIA','AC','68'),
('BRASILIA','DF','61'),
('BREJINHO','RN','84'),
('BUTANTA','SP','11'),
('BUZIOS','RJ','22'),
('CABEDELO','PB','83'),
('CABO FRIO','RJ','22'),
('CACERES','MT','65'),
('CACHOEIRA PAULISTA','SP','12'),
('CACHOEIRO DE ITAPEMIRIM','ES','28'),
('CACOAL','RO','69'),
('CAETITE','BA','77'),
('CAIAPONIA','GO','64'),
('CAICO','RN','84'),
('CAJAZEIRAS','PB','83'),
('CALDAS NOVAS','GO','64'),
('CAMACARI','BA','71'),
('CAMARAGIBE','PE','81'),
('CAMBORIU','SC','47'),
('CAMOCIM','CE','88'),
('CAMPINA GRANDE','PB','83'),
('CAMPINAS','SP','19'),
('CAMPO FORMOSO','BA','74'),
('CAMPO GRANDE','MS','67'),
('CAMPO MAIOR','PI','86'),
('CAMPO MOURAO','PR','44'),
('CAMPO VERDE','MT','66'),
('CAMPOS DOS GOYTACAZES','RJ','22'),
('CANARANA','MT','66'),
('CANDIDO MOTA','SP','18'),
('CANINDE','CE','85'),
('CANOAS','RS','51'),
('CARAJAS','PA','91'),
('CARAPICUIBA','SP','11'),
('CARAUBAS','RN','84'),
('CARMOPOLIS','SE','79'),
('CAROLINA','MA','99'),
('CARPINA','PE','81'),
('CARUARU','PE','81'),
('CASAPAVA','SP','12'),
('CASSILANDIA','MS','67'),
('CASTANHAL','PA','91'),
('CASTELO','ES','28'),
('CASTRO','PR','42'),
('CATALÃO','GO','64'),
('CATANDUVA','SP','17'),
('CATU','BA','71'),
('CAXIAS','MA','99'),
('CAXIAS DO MARANHAO','MA','99'),
('CAXIAS DO SUL','RS','54'),
('CEDRO','PE','87'),
('CESARIO LANGE','SP','15'),
('CHAPECO','SC','49'),
('CIANORTE','PR','44'),
('CICERO DANTAS','BA','75'),
('COUTO DE MAGALHÃES','TO','63'),
('COCAL','RO','69'),
('CODO','MA','99'),
('COLATINA','ES','27'),
('COLINAS','MA','99'),
('CONCEICAO','PB','83'),
('CONCEICAO DO ARAGUAIA','PA','94'),
('CONCORDIA','SC','49'),
('CORNELIO PROCOPIO','PR','43'),
('CONTAGEM','MG','31'),
('COROATÁ','MA','99'),
('CORONEL FABRICIANO','MG','31'),
('CORUMBA','MS','67'),
('COTIA','SP','11'),
('COXIM','MS','67'),
('CRATEUS','CE','88'),
('CRATO','CE','88'),
('CRICIUMA','SC','48'),
('CRISTALINA','GO','61'),
('CRUZ ALTA','RS','55'),
('CRUZ DAS ALMAS','BA','75'),
('CRUZEIRO','SP','12'),
('CRUZEIRO DO SUL','AC','68'),
('CUBATÃO','SP','13'),
('CUIABA','MT','65'),
('CURITIBA','PR','41'),
('CURRAIS NOVOS','RN','84'),
('DIADEMA','SP','11'),
('DIRCE REIS','SP','17'),
('DIVINOPOLIS','MG','37'),
('DOURADOS','MS','67'),
('DUQUE DE CAXIAS','RJ','21'),
('EDEIA','GO','64'),
('ELDORADO','MS','67'),
('ELDORADO DO SUL','RS','51'),
('ERECHIM','RS','54'),
('ESTANCIA','SE','79'),
('EUNAPOLIS','BA','73'),
('FARROUPILHA','RS','54'),
('FARTURA','SP','14'),
('FATIMA DO SUL','MS','67'),
('NOVA SERRANA','MG','37'),
('FERNANDO DE NORONHA','PE','81'),
('FLORES DA CUNHA','RS','54'),
('FLORIANO','PI','89'),
('FLORIANOPOLIS','SC','48'),
('FORMOSA','GO','61'),
('FORTALEZA','CE','85'),
('FOZ DO IGUACU','PR','45'),
('FRANCA','SP','16'),
('FRANCISCO MORATO','SP','11'),
('GAIATUBA','GO','62'),
('GAMA','DF','61'),
('GANDU','BA','73'),
('GARANHUNS','PE','87'),
('GASPAR','SC','47'),
('GOIANESIA','GO','62'),
('GOIANIA','GO','62'),
('GOIANINHA','RS','84'),
('GOIAS','GO','62'),
('GOVERNADOR VALADARES','MG','33'),
('GRAMADO','RS','54'),
('GUAJARA MIRIM','RO','69'),
('GUANAMBI','BA','77'),
('GUARABIRA','PB','83'),
('GUARAPARI','ES','27'),
('GUARAPUAVA','PR','42'),
('GUARATINGUETA','SP','12'),
('GUARUJA','SP','13'),
('GUARULHOS','SP','11'),
('GURUPI','TO','63'),
('HUMAITA','AM','97'),
('IBATIBA','ES','28'),
('IBIRUBA','RS','54'),
('IJUI','RS','55'),
('ILHEUS','BA','73'),
('IMPERATRIZ','MA','99'),
('INDAIATUBA','SP','19'),
('IPAMERI','GO','64'),
('IPATINGA','MG','31'),
('IPIAU','BA','73'),
('IPIRA','BA','75'),
('IPIRANGA','SP','16'),
('IPORA','GO','64'),
('IRECE','BA','74'),
('ITABERABA','BA','75'),
('ITABIRA','MG','31'),
('ITABUNA','BA','73'),
('ITACARE','BA','73'),
('ITACOATIARA','AM','92'),
('ITAITUBA','PA','93'),
('ITAJAI','SC','47'),
('ITAJUBÁ','MG','35'),
('ITAMARAJU','BA','73'),
('ITAMBE','PR','41'),
('ITAPAJE','CE','85'),
('ITAPECIRICA DA SERRA','SP','11'),
('ITAPERUNA','RJ','22'),
('ITAPETINGA','BA','77'),
('ITAPETININGA','SP','15'),
('ITAPIPOCA','CE','85'),
('ITAPORA','MS','67'),
('ITAPURANGA','GO','62'),
('ITARANA','ES','27'),
('ITAUNA','MG','37'),
('ITIQUIRA','MT','65'),
('ITU','SP','11'),
('ITUIUTABA','MG','34'),
('ITUMBIARA','GO','64'),
('JABOATAO','PE','81'),
('JABOTICABAL','SP','16'),
('JACAREÍ','SP','12'),
('JACIARA','MT','66'),
('JACOBINA','BA','74'),
('JACUNDA','PA','94'),
('JAGUAQUARA','BA','73'),
('JAGUARAO','RS','53'),
('JARAGUA','SC','47'),
('JATAI','GO','64'),
('JAU','SP','14'),
('JEQUIE','BA','73'),
('JEREMOABA','BA','75'),
('JI- PARANA','RO','69'),
('JOACABA','SC','49'),
('JOAO NEIVA','ES','27'),
('JOAO PESSOA','PB','83'),
('JOINVILLE','SC','47'),
('JUARA','MT','66'),
('JUAZEIRO','BA','74'),
('JUAZEIRO DO NORTE','CE','88'),
('JUINA','MT','66'),
('JUIZ DE FORA','MG','32'),
('JUNDIAI','SP','11'),
('JUSSARA','GO','62'),
('LABREA','AM','97'),
('LAGARTO','SE','79'),
('LAJES','SC','49'),
('LAGO DA PEDRA','MA','99'),
('LAGOA NOVA','RN','84'),
('LAJEDO','PE','87'),
('LARANJAL DO JARI','AP','96'),
('LAURO DE FREITAS','BA','71'),
('LAVRAS','MG','35'),
('LIMEIRA','SP','19'),
('LIMOEIRO DO NORTE','CE','85'),
('LINHARES','ES','27'),
('LONDRINA','PR','43'),
('LORENA','SP','12'),
('LUCAS DO RIO VERDE','MT','65'),
('LUZIANIA','GO','62'),
('MACAE','RJ','22'),
('MACAPA','AP','96'),
('MACAUBAL','SP','17'),
('MACEIO','AL','82'),
('MAFRA','SC','47'),
('MAIRIPORÃ','SP','11'),
('MALBORO','MA','50'),
('MANACAPURU','AM','92'),
('MANAUS','AM','92'),
('MARABA','PA','94'),
('MARACAJU','MS','67'),
('MARICA','RJ','21'),
('MARILIA','SP','14'),
('MARINGA','PR','44'),
('MATAO','SP','16'),
('MATUPA','MT','66'),
('MIAMI','FL','05'),
('MIGUEL PEREIRA','RJ','24'),
('MIRACEMA DO TOCANTINS','TO','63'),
('MIRADOR','MA','99'),
('MIRASOL','SP','17'),
('MIRASSOL D\'OESTE','MT','65'),
('MOGI DAS CRUZES','SP','11'),
('MONTE MOR','SP','19'),
('MONTEIRO','PB','83'),
('MONTES CLAROS','MG','38'),
('MORADA NOVA','CE','85'),
('MORRINHOS','GO','64'),
('MOSSORO','RN','84'),
('MUNDO NOVO','MS','67'),
('NATAL','RN','84'),
('NAVIRAI','MS','67'),
('NEPOMUCENO','MG','35'),
('NEWARK','NJ','97'),
('NILOPOLIS','RJ','21'),
('NITEROI','RJ','21'),
('NORTEANDIA','MT','65'),
('NOVA ANDRADINA','MS','67'),
('NOVA CRUZ','RN','84'),
('NOVA FRIBURGO','RJ','22'),
('NOVA IGUACU','RJ','21'),
('NOVA XAVANTINA','MT','66'),
('NOVO HAMBURGO','RS','51'),
('MESQUITA','RJ','21'),
('OLINDA','PE','81'),
('ORIXIMINA','PA','93'),
('OSASCO','SP','11'),
('OURINHOS','SP','14'),
('OURO PRETO','MG','31'),
('PACAJUS','CE','85'),
('PALMARES','PE','81'),
('PALMAS','TO','63'),
('PALMEIRA DOS INDIOS','AL','82'),
('PARA DE MINAS','MG','37'),
('PARACURU','CE','85'),
('PARAGOMINAS','PA','91'),
('PARAISO DO TOCANTINS','TO','63'),
('PARAUAPEBAS','PA','94'),
('PARINTINS','AM','92'),
('PARNAIBA','PI','86'),
('PARNAMIRIM','PE','87'),
('PASSO FUNDO','RS','54'),
('PASSOS','MG','35'),
('PATO BRANCO','PR','46'),
('PATOS','PB','83'),
('PATOS DE MINAS','MG','34'),
('PAULINIA','SP','19'),
('PAULO AFONSO','BA','75'),
('PEDREIRAS','MG','38'),
('PEDRO LEOPOLDO','MG','31'),
('PELOTAS','RS','53'),
('PENEDO','AL','82'),
('PESQUEIRA','PE','87'),
('PETROLANDIA','PE','87'),
('PETROLINA','PE','87'),
('PETROPOLIS','RJ','24'),
('PICOS','PI','89'),
('PINDAMONHANGABA','SP','12'),
('PINHEIRO','MA','98'),
('PIRASUNUNGA','SP','19'),
('PIRAI','RJ','21'),
('PIRES DO RIO','GO','64'),
('PIRIPIRI','PI','86'),
('POCOS DE CALDAS','MG','35'),
('PONTA GROSSA','PR','42'),
('PONTA PORA','MS','67'),
('PONTES E LARCEDA','MT','65'),
('PORANGATU','GO','62'),
('PORCAO DE PEDRA','MA','99'),
('PORCIUNCULA','RJ','22'),
('PORTO ALEGRE','RS','51'),
('PORTO NACIONAL','TO','63'),
('PORTO TROMBETAS','PA','93'),
('PORTO VELHO','RO','69'),
('POUSO ALEGRE','MG','35'),
('POXOREO','MT','66'),
('PRAIA GRANDE','SP','13'),
('PRESIDENTE MEDICI','RO','69'),
('PRESIDENTE PRUDENTE','SP','18'),
('PRESIDENTE VENCESLAU','SP','18'),
('PRIMAVERA DO LESTE','MT','66'),
('PROPRIA','SE','79'),
('QUEIMADOS','RJ','21'),
('QUIRINOPOLIS','GO','64'),
('RECIFE','PE','81'),
('REDENCAO','PA','94'),
('RESENDE','RJ','24'),
('RIACHO DE SANTANA','BA','77'),
('RIALMA','GO','62'),
('RIBEIRA DO POMBAL','BA','75'),
('RIBEIRAO PRETO','SP','16'),
('RIO BONITO','RJ','24'),
('RIO BRANCO','AC','68'),
('RIO BRILHANTE','MS','67'),
('RIO CLARO','SP','19'),
('RIO DAS OSTRAS','RJ','22'),
('RIO DE JANEIRO','RJ','21'),
('RIO DO SUL','SC','47'),
('RIO GRANDE','RS','53'),
('RIO VERDE','GO','64'),
('ROLIM DE MOURA','RO','69'),
('RONDON DO PARA','PA','94'),
('RONDONOPOLIS','MT','66'),
('RUI BARBOSA','BA','71'),
('RUSSAS','CE','85'),
('SALGUEIRO','PE','87'),
('SALVADOR','BA','71'),
('SANTA BARBARA DO OESTE','SP','19'),
('SANTA CRUZ','RS','51'),
('SANTA CRUZ DAS PALMEIRAS','SP','19'),
('SANTA CRUZ DO SUL','RS','51'),
('SANTA INES','MA','98'),
('SANTA ISABEL','SP','11'),
('SANTA MARIA','RS','55'),
('SANTA MARIA DA VITORIA','BA','77'),
('SANTA RITA','PB','83'),
('SANTA RITA DO SAPUCAI','MG','35'),
('SANTA ROSA','RS','55'),
('SANTAREM','PA','93'),
('SANTO AMARO','SP','11'),
('SANTO ANGELO','RS','55'),
('SANTO ANDRE','SP','11'),
('SANTO ANTONIO DA PLATINA','PR','43'),
('SANTOS','SP','13'),
('SAO BERNARDO DO CAMPO','SP','11'),
('SAO CAETANO DO SUL','SP','11'),
('SAO CARLOS','SP','16'),
('SAO CRISTOVAO','SE','79'),
('SAO DOMINGOS DO MARANHAO','MA','99'),
('SAO FIDELIS','RJ','22'),
('SAO JOAO DA BARRA','RJ','22'),
('SAO JOSE','SC','48'),
('S. JOSE  RIO PRETO','SP','17'),
('SAO JOSE DOS CAMPOS','SP','12'),
('SAO JOSÉ DOS PINHAIS','PR','41'),
('SAO LEOPOLDO','RS','51'),
('SAO LOURENCO','MG','35'),
('SAO LUIS','MA','98'),
('SAO LUIS DE MONTES BELOS','GO','64'),
('SÃO MATEUS','ES','27'),
('SAO MIGUEL  DOS CAMPOS','AL','82'),
('SAO PAULO','SP','11'),
('SAO PEDRO','SP','19'),
('SAO PEDRO DA ALDEIA','RJ','22'),
('SAO RAIMUNDO NONATO','PI','86'),
('SAO VICENTE','SP','13'),
('SAPUCAIA DA SERRA','RS','51'),
('SAQUAREMA','RJ','22'),
('SENADOR GUIOMARD','AC','68'),
('SENADOR POMPEU','CE','88'),
('SENHOR DO BONFIM','BA','75'),
('SERGIPE','SE','79'),
('SERRA','ES','27'),
('SERRA BRANCA','PA','83'),
('SERRA DOS CARAJAS','PA','94'),
('SERRA TALHADA','PE','87'),
('SERRINHA','BA','75'),
('SERTANIA','PE','87'),
('SETE LAGOAS','MG','31'),
('SINOP','MT','66'),
('SOBRAL','CE','85'),
('SOROCABA','SP','15'),
('SORRISO','MT','66'),
('SOUSA','PB','83'),
('SUMARÉ','SP','19'),
('SURUBIM','PE','81'),
('SUZANO','SP','11'),
('TABOÃO DA SERRA','SP','11'),
('TAGUATINGA','DF','61'),
('TANGARA DA SERRA','MT','65'),
('TAUA','CE','85'),
('TAUBATE','SP','12'),
('TEFE','AM','97'),
('TEIXEIRA DE FREITAS','BA','73'),
('TEOFILO OTONI','MG','33'),
('TERESINA','PI','86'),
('TERESOPOLIS','RJ','21'),
('TERRA NOVA DO NORTE','MT','66'),
('TEXEIRA DE FREITAS','BA','73'),
('TIANGUA','CE','88'),
('TIETÊ','SP','15'),
('TIMON','MA','86'),
('TIMOTEO','MG','31'),
('TIRADENTES','MG','32'),
('TOBIAS  BARRETO','SE','79'),
('TOCANTINS','TO','63'),
('TOLEDO','PR','45'),
('TRES CORACOES','MG','35'),
('TRES LAGOAS','MS','67'),
('TRES MARIAS','MG','38'),
('TRES PASSOS','RS','55'),
('TUBARAO','SC','48'),
('TUCUMA','PA','94'),
('TUCURUI','PA','94'),
('TUPARENDI','RS','55'),
('UBERABA','MG','34'),
('UBERLANDIA','MG','34'),
('UMUARAMA','PR','44'),
('UNAÉ','MG','38'),
('URUPÊS','SP','17'),
('URUGUAIANA','RS','55'),
('VACARIA','RS','54'),
('VALENÇA','BA','75'),
('VARGINHA','MG','35'),
('VARZEA ALEGRE','CE','85'),
('VARZEA GRANDE-MT','MT','65'),
('VESPASIANO','MG','31'),
('VICENTINA','MS','67'),
('VICOSA','MG','31'),
('VIGIA','PA','91'),
('VILHENA','RO','69'),
('VITORIA','ES','27'),
('VITORIA DA CONQUISTA','BA','77'),
('VITORIA DE SANTO ANTAO','PE','81'),
('VITORIA DO MEARIM','MA','98'),
('VOLTA REDONDA','RJ','24'),
('VOTUPORANGA','SP','17'),
('CAMUTANGA','PE','81'),
('SOMBRIO','SC','48'),
('DUMONT','SP','16'),
('POMPANO BEACH','FL','04'),
('CAÇAPAVA','SP','12'),
('COLORADO','PR','44'),
('FRUTAL','MG','34'),
('BIRIGUI','SP','18'),
('ESPIRITO SANTO DO PINHAL','SP','19'),
('AROEIRAS','PB','83'),
('GLORIA DE DOURADOS','MS','67'),
('UBATUBA','SP','12'),
('NOVA ERECHIM','SC','49'),
('ITATIBA','SP','11'),
('TATUI','SP','15'),
('SAO FRANCISCO DO SUL','SC','47'),
('CUPARAQUE','MG','33'),
('BELO ORIENTE','MG','31'),
('ANANINDEUA','PA','91'),
('JALES','SP','17'),
('CACHOEIRA DO SUL','RS','51'),
('AVANHANDAVA','SP','18'),
('FREDERICO WESTPHALEN','RS','55'),
('FORMIGA','MG','37'),
('BAIXO GUANDU','ES','27'),
('VALINHOS','SP','19'),
('ITAU DE MINAS','MG','35'),
('NOVA MUTUM','MT','65'),
('EXTREMA','MG','35'),
('OSORIO','RS','51'),
('PERDIZES','SP','11'),
('PIRAJU','SP','14'),
('TRES RIOS','RJ','24'),
('CURURUPU','MA','98'),
('VINHEDO','SP','19'),
('GOIANA','PE','81'),
('CASCAVEL','PR','45'),
('CANAA DOS CARARAJAS','PA','94'),
('TUPACIGUARA','MG','34'),
('SAO JOAO DE MERITI','RJ','21'),
('IVAIPORA','PR','43'),
('SAO MATEUS DO SUL','PR','42'),
('PALHOÇA','SC','48'),
('ITABIRITO','MG','31'),
('GOIANESIA DO PARA','PA','94'),
('MEDIANEIRA','PR','45'),
('EUZEBIO','CE','85'),
('CAPANEMA','PA','91'),
('PARAMBU','CE','99'),
('HORTOLANDIA','SP','19'),
('CEILANDIA','DF','61'),
('HORIZONTINA','RS','55'),
('SANTANA DE PARNAIBA','SP','11'),
('JAGUARE','ES','27'),
('SANTANA','BA','77'),
('JANDAIA DO SUL','PR','44'),
('CARATINGA','MG','33'),
('UNIAO DA VITORIA','PR','42'),
('TAMBAÚ','SP','19'),
('SÃO SEPÉ','RS','55'),
('JANUÁRIO','MG','38'),
('MOCOCA','SP','19'),
('ATIBAIA','SP','11'),
('CARNEIRINHO','MG','34'),
('SÃO JOÃO DEL REI','MG','32'),
('OLHO D`ÁGUA DAS FLORES','AL','82'),
('LINS','SP','14'),
('SANTA CRUZ DO CAPIBARIBE','PE','81'),
('SÃO FRANCISO','MG','38'),
('MAUA','SP','11'),
('LAJEADO','RS','51'),
('SÃO GONÇALO','RJ','21'),
('SERTANÓPOLIS','PR','43'),
('SANTA GERTRUDES','SP','19'),
('SANTANA DO PARNAÍBA','SP','11'),
('GOIOERÊ','PR','44'),
('PARAIBUNA','SP','12'),
('BEBEDOURO','SP','17'),
('CABROBRÓ','PE','87'),
('SABARA','MG','31'),
('FEIRA DE SANTANA','BA','75'),
('NOVO HORIZONTE','SP','17'),
('BARRA BONITA','SP','14'),
('MOGI MIRIM','SP','19'),
('PIRACICABA','SP','19'),
('LENÇOIS PAULISTAS','SP','14'),
('CATUNDA','CE','88'),
('ENGENHEIRO COELHO','SP','19'),
('CHAPADÃO DO SUL','MS','67'),
('PIRABORA','MG','38'),
('CAMBUÍ','MG','35'),
('REGISTRO','SP','13'),
('ANDRADAS','MG','35'),
('SANTA VITÓRIA','MG','34'),
('RIBEIRÓPOLIS','SE','79'),
('VIANA','MA','98'),
('PARANAVAÍ','PR','44'),
('PLANALTINA','DF','61'),
('JACANÃ','SP','11'),
('PANAMBI','RS','55'),
('VILA VELHA','ES','27'),
('ILHA SOLTEIRA','SP','18'),
('SÃO MANOEL','SP','14'),
('GUIRICEMA','MG','32'),
('SERTÃOZINHO','SP','16'),
('SANTO ANTONIO DO MONTE','MG','37'),
('SERRO','MG','38'),
('BATATAIS','SP','16'),
('ITAMARANDIBA','MG','38'),
('MACOCO','RJ','22'),
('JAGUARIAÍVA','PR','43'),
('VALENTE','BA','75'),
('BANDEIRANTES','PR','43'),
('TANABI','SP','17'),
('ARCOS','MG','37'),
('JARAGUA DO SUL','SC','47'),
('CARANGOLA','MG','32'),
('JARDIM','MS','67'),
('VILA NOVA CONCEIÇÃO','SP','11'),
('BELFORD ROXO','RJ','21'),
('OLIMPIA','SP','17'),
('CONSELHEIRO LAFAIETE','MG','31'),
('SOLEDADE','RS','54'),
('BARBALHA','CE','88'),
('VIDEIRA','SC','49'),
('JUAÇABA','SC','49'),
('PORTO UNIAO','SC','42'),
('ITAPEVA','SP','15'),
('FERRAZ DE VASCONCELOS','SP','11'),
('SAO JOAO  NEPONUCENO','MG','32'),
('BARCARENA','PA','91'),
('ITAQUAQUECETUBA','SP','11'),
('MORRINHOS  -CE','CE','88'),
('XANXERE','SC','49'),
('SAO JOAQUIM','SC','49'),
('CURUPI','TO','63'),
('UTINGA','BA','75'),
('CARIACICA','ES','27'),
('IMBUIA','SC','47'),
('CATAGUASES','MG','32'),
('CAPIVARI','SP','19'),
('PATROCINIO','MG','34'),
('SANTA CATARINA','SC','49'),
('SOBRADINHO','DF','61'),
('SAO FRANCISCO DE ITABAPUA','RJ','22'),
('GUAIRAÇA','PR','44'),
('CARUTAPERA','MA','98'),
('TRINDADE','GO','62'),
('TEUTONIA','RS','51'),
('CRISTAIS','MG','35'),
('RERIATUBA','CE','88'),
('POA','SP','11'),
('JAGUARIUNA','SP','19'),
('AREIA','PB','83'),
('CONCEIÇÃO DO COITE','BA','75'),
('ITAOCARA','RJ','22'),
('ALEGRETE','RS','55'),
('FAROLANDIA','SE','79'),
('MACUCO','RJ','22'),
('FLORES DE CUNHA','RS','54'),
('MURIAÉ','MG','32'),
('SANTANA DO ACARAÚ','CE','88'),
('PENHA','SC','47'),
('BREVES','PA','91'),
('MARCELANDIA','MT','66'),
('PALMEIRANDIA','MA','98'),
('MILPITAS','CA','32'),
('SARANDI','PR','44'),
('PINHAIS','PR','41'),
('CANOINHA','SC','47'),
('NOVA ODESSA','SP','19'),
('CANDEIAS','MG','35'),
('MARAPA','PR','94'),
('JABOATAO DOS GUARARAPES','PE','81'),
('RONDONIA','RO','69'),
('VERA','MT','66'),
('PORTO FERREIRA','SP','19'),
('VALENCA','RJ','24'),
('PARATY','RJ','24'),
('SAO JOAO DO ORIENTE','MG','33'),
('IBIA','MG','34'),
('CAPINZAL','SC','49'),
('GUAXUPE','MG','35'),
('SAO FRANCISCO DE ASSIS','RS','55'),
('COXIPO','MT','65'),
('TAILANDIA','PA','91'),
('TAMANDARÉ','PR','41'),
('ALAMEDA TAMANDARÉ','PR','41'),
('JURITI','PA','93'),
('PORTEIRINHA','MG','38'),
('PITUBA','BA','71'),
('IÇARA','SC','48'),
('CAMETA','PA','91'),
('MONEIROS DO TIETE','SP','17'),
('BOA VISTA DO RAMOS','AM','92'),
('CURIUVA','PR','43'),
('VITORINO FREIRE','MA','98'),
('PAU DOS FERROS','RN','84'),
('TAPURAH','MT','66'),
('bannach','PA','94'),
('ICÓ','CE','88'),
('CARMO DA MATA','MG','37'),
('SÃO JOÃO DA BOA VISTA','SP','19'),
('NOVA LIMA','MG','31'),
('CAMPO ALEGRE','SC','47'),
('SÃO SEBASTIÃO VIÇOSA','MG','31'),
('ARAPONGAS','PR','43'),
('PIMENTA BUENO','RO','69'),
('COSMOPÓLIS','SP','19'),
('UBAPORANGA','MG','33'),
('GETULIO VARGAS','RS','54'),
('DIANOPOLIS','TO','63'),
('IRANI','SC','49'),
('MONTE ALTO','SP','16'),
('ALTO ARAGUAIA','MT','66'),
('JAGUARARI','BA','74'),
('MARCO','CE','88'),
('BRUSQUE','SC','47'),
('SANTO ANTONIO DE PADUA','RJ','22'),
('FRANCISCO BELTRAO','PR','46'),
('LAGOA SANTA','MG','35'),
('LAGES','SC','49'),
('CACHOEIRINHA','RS','51'),
('IPUÃ','SP','16'),
('TERRA ROCHA','PR','44'),
('PARAIBA DO SUL','RJ','24'),
('SANTA TERESA','ES','27'),
('SAO BORJA','RS','55'),
('CASA BRANCA','SP','19'),
('SANTANA','AP','96'),
('QUATRO BARRAS','PR','41'),
('ESTRELA D\' OESTE','SP','17'),
('QUIXERAMOBIM','CE','88'),
('AFOGADOS','PE','81'),
('SAPUCAIA DO SUL','RS','51'),
('TRINDADE','PE','87'),
('FRAIBURGO','SC','49'),
('CANELAS','RS','54'),
('IPEUNA','SP','19'),
('ALTO BELA VISTA','SC','49'),
('SÃO GABRIEL','RS','55'),
('Ipumirim','SC','49'),
('CARANDAI','MG','32'),
('MONTENEGRO','RS','51'),
('SIMÕES FILHO','BA','71'),
('FRIBURGO','RJ','22'),
('JARU','RO','69'),
('XAXIM','SC','49'),
('CANAVIEIRAS','BA','73'),
('NOVA OLINDA DO NORTE','AM','92'),
('MINEIROS DO TIETE','SP','14'),
('COLINAS DO TOCANTINS','TO','63'),
('ROSARIO DO SUL','RS','55'),
('MIRAMAR','FL','54'),
('NOVA VENECIA','ES','27'),
('SAPIRANGA','RS','51'),
('SAO BENTO','MA','98'),
('ARRAIAL DO CABO','RJ','22'),
('ALVARES MACHADO','SP','18'),
('PERUIBE','SP','13'),
('ESPERA FELIZ','MG','32'),
('ARAUCARIA','PR','41'),
('CAÇAPAVA DO SUL','RS','55'),
('SAO JOAO DO POLESINE','RS','55'),
('PONTAL','SP','16'),
('São Gotardo','MG','34'),
('BENTO GOLCALVES','RS','54'),
('CASIMIRO DE ABREU','RJ','22'),
('ALTO TAQUARI','MT','66'),
('ADRIANÓPOLIS','AM','92'),
('DIAMANTINA','MG','38'),
('Vila Canaã','GO','62'),
('SÃO MIGUEL DO GUAMÁ','PA','91'),
('ANDIRA','PR','43'),
('POMERODE','SC','47'),
('COLNIZA','MT','66'),
('SÃO JOSÉ DE RIBAMAR','MA','98'),
('COSTA RICA','MS','67'),
('URUSSANGA','SC','48'),
('SAO SEBASTIAO','SP','12'),
('SANTA TEREZINHA','PB','83'),
('PARACATU','MG','38'),
('CANTAGALO','PR','42'),
('PEDREIRAS','MA','99'),
('CAPITAO POÇO','PA','91'),
('Tupanciretã','RS','55'),
('CARLOS BARBOSA','RS','54'),
('ANTA GORDA','RS','51'),
('ALMEIRIM','PA','93'),
('NOVA CAMPINAS','SP','11'),
('TOCANTINS','MG','32'),
('ASSU','RN','84'),
('LAGOINHA','MG','31'),
('COLIDER','MT','66'),
('URUARÁ','PA','93'),
('OURILANDIA DO NORTE','PA','94'),
('Paranaguá','PR','41'),
('ITAGUAI','RJ','21'),
('SAO RAIMUNDO DAS MANGABEI','MA','99'),
('ARAPOTI','PR','43'),
('Bombinhas','SC','47'),
('APERIBE','RJ','22'),
('VALPARAISO DE GOIAS','GO','61'),
('MARITUBA','PA','91'),
('IBIPORÃ','PR','43'),
('SÃO JOSÉ DO RIO PRETO','SP','17'),
('ANDRELANDIA','MG','35'),
('PALMITOS','SC','49'),
('ITAPEVI','SP','11'),
('VIO AZUL','PI','98'),
('RESPLENDOR','MG','33'),
('AÇAILÂNDIA','MA','99'),
('MARTINS SOARES','MG','33'),
('TRIZIDELA DO VALE','MA','99'),
('SERRA DOURADA','BA','77'),
('SAO SEBASTIAO DO CAI','RS','51'),
('TAQUARITINGA','SP','16'),
('BIGUACU','SC','48'),
('MANGARATIBA','RJ','24'),
('MARIANA','MG','31'),
('TUPANDI','RS','51'),
('PARANÁ','PR','41'),
('Monte Carmelo','MG','34'),
('SAO MIGUEL D\'OESTE','SC','49'),
('Pirapetinga','MG','32'),
('VERANOPOLIS','RS','54'),
('MUZAMBINHO','MG','35'),
('GUARAREMA','SP','11'),
('ITAPECERICA DA SERRA','SP','11'),
('Novo Diamantino','MT','65'),
('MACAU','RN','84'),
('Andradina','SP','18'),
('BOCAIUVA','MG','38'),
('TOMAZINA','PR','43'),
('JOSE BONIFACIO','SP','17'),
('ANGICAL','BA','77'),
('Pouso Redondo','SC','47'),
('CATOLE DO ROCHA','PB','83'),
('LARANJEIRAS','SE','79'),
('PEIXOTO DE AZEVEDO','MT','66'),
('BARRA DO CHOCA','BA','77'),
('LEME','SP','19'),
('Rio Negrinho','SC','47'),
('PORTO SEGURO','BA','73'),
('CABO DE SANTO AGOSTINHO','PE','81'),
('GUARANHUNS','AC','87'),
('guara','SP','16'),
('PENAPOLIS','SP','18'),
('UBA','MG','32'),
('MORRO AGUDO','SP','16'),
('CONFRESA','MT','66'),
('CONGONHAS','MG','31'),
('SÃO SIMÃO','SP','16'),
('PORTO FIRME','MG','31'),
('PIUMA','ES','28'),
('LIMOEIRO','PE','81'),
('CAJATI','SP','13'),
('cajueiro','AL','83'),
('GUANHAES','MG','33'),
('PAULISTA','PE','81'),
('VOTORANTIM','SP','15'),
('UNAI','MG','38'),
('MACATUBA','SP','14'),
('SARANDI RS','RS','54'),
('TRES PONTAS','MG','35'),
('BURITAMA','SP','18'),
('Santana do Araguaia','PA','94'),
('GLORINHA','RS','51'),
('ITARANTIM','BA','73'),
('ANICUNS','GO','64'),
('MAGE','RJ','21'),
('JANDIRA','SP','11'),
('SAO FELIX','BA','75'),
('VARGEM GRANDE PAULISTA','SP','11'),
('Arroio do Sal','RS','51'),
('Coronel Murta','MG','33'),
('PIUMHI','MG','37'),
('OURO FINO','MG','35'),
('QUERENCIA','MT','66'),
('SANTA LUZIA','MG','31'),
('LAGO VERDE','MA','99'),
('TRES COROAS','RS','51'),
('ITAPACI','GO','62'),
('SAO SEBASTIAO DO PARAISO','MG','35'),
('MUQUI','ES','28'),
('Itanhaém','SP','13'),
('SÃO JOÃO BATISTA','SC','48'),
('TELÊMACO BORBA','PR','42'),
('APARECIDA DO RIO DOCE','GO','64'),
('PRATA','MG','34'),
('AVARE','SP','14'),
('BERTIOGA','SP','13'),
('MOGIGUAÇU','SP','19'),
('COARACI','BA','73'),
('POMPEIA','SP','14'),
('PACO DO LUMIAR','MA','98'),
('CAMPOS SALES','CE','88'),
('NOBRES','MT','65'),
('INDAIAL','SC','47'),
('CARAZINHO','RS','54'),
('Poconé','MT','65'),
('Campo Novo do Parecis','MT','65'),
('Cerejeiras','RO','69'),
('Nova Marabá','PA','94'),
('MACHADINHO D\'OESTE','RO','69'),
('Simão Dias','SE','79'),
('MARAGOGI','AL','82'),
('CAMPO LARGO','PR','41'),
('CARAGUATATUBA','SP','12'),
('São Sebastião Boa Vista','PA','91'),
('Marechal Cândido Rondon','PR','45'),
('ABRE CAMPO','MG','31'),
('Porto dos Gauchos','MT','66'),
('COELHO NETO','MA','98'),
('ALVORADA','RS','51'),
('Boqueirão','PB','83'),
('Iuna','ES','28'),
('SANTANA DO LIVRAMENTO','RS','55'),
('SAO SEBASTIAO DA BOA VIST','PA','91'),
('CORDEIRO','RJ','22'),
('CAMBE','PR','43'),
('NAO-ME-TOQUE','RS','54'),
('IPOJUCA','PE','81'),
('TRÊS BARRAS','SC','47'),
('MORRO DA FUMAÇA','SC','48'),
('ABREU E LIMA','PE','81'),
('AGUAS DE LINDOIA','SP','19'),
('SILVEIRA MARTINS','RS','55'),
('FELIXLÂNDIA','MG','31'),
('Sarandi','BA','71'),
('VIAMAO','RS','51'),
('IBIRITE','MG','31'),
('SANTA LUZIA DO ITANHY','SE','79'),
('TURUMÃ','SP','18'),
('salinas','MG','38'),
('Cravinhos','SP','16'),
('Campina Grande do Sul','PR','41'),
('ARARUNA','PB','83'),
('SAO JOSE DA LAPA','MG','31'),
('TRÊS FIGEUIRAS','RS','51'),
('CORRENTINA','BA','77'),
('Rio Grande da Serra','SP','11'),
('MANTENA','MG','33'),
('MONTE AZUL','MG','38'),
('GUARIBA','SP','16'),
('MORRO DO CHAPÉU','BA','74'),
('PEDRO CANÁRIO','ES','27'),
('CAMPOS DE JULIO','MT','65'),
('MACAIBA','RN','84'),
('BOM JARDIM','PE','81'),
('CELEBRATION','VM','05'),
('AGUDOS','SP','14'),
('Barra de São Francisco','ES','27'),
('OURO BRANCO','MG','31'),
('TUPÃ','SP','14'),
('SANTA HELENA','MA','98'),
('FERNANDOPOLIS','SP','17'),
('UNIÃO DO PALMARES','AL','82'),
('QUEIMADAS','PB','63'),
('TAQUARA','RS','51'),
('CORRETINA','BA','77'),
('LAPÃO','BA','74'),
('Parangatu','GO','62'),
('Rio Piracicaba','MG','31'),
('SANTA HELENA DE GOIAIS','GO','64'),
('BOM JESUS','GO','62'),
('ESPINOSA','MG','38'),
('CAMPO BOM','RS','51'),
('Santana do Ipanema','AL','82'),
('TAPES','RS','51'),
('BRUMADINHO','MG','31'),
('SANTA BARBARA D\'OESTE','SP','19'),
('IMBE','RS','51'),
('BRASILIA DE MINAS','MG','38'),
('PLANALTO','RS','55'),
('MARACACUME\'','MA','98'),
('REALEZA','PR','46'),
('MANGUEIRINHA','PR','46'),
('CAMPOERE','SC','49'),
('SANTA LUZIA','MA','98'),
('CURVELO','MG','38'),
('Almirante Tamandaré','PR','41'),
('LAGUNA','SC','48'),
('BREJO SANTO','CE','88'),
('RIBEIRÃO DAS NEVES','MG','31'),
('Vargem Grande','MA','98'),
('TAPEJARA','PR','44'),
('BROTAS','SP','14'),
('ITABORAI','RJ','21'),
('GUARANTA DO NORTE','MT','66'),
('RIO GRANDE DO SUL','RS','51'),
('NORTELÂNDIA','MT','65'),
('SENADOR CANEDO','GO','62'),
('Balsa Nova','PR','41'),
('BRASNORTE','MT','66'),
('CARMO DO RIO CLARO','MG','35'),
('CAMAQUA','RS','51'),
('RIO GRANDE DO NORTE','RN','84'),
('SÃO ROQUE','SP','11'),
('SÃO DESIDÉRIO','BA','77'),
('PARA','PA','94'),
('CAMPOS ELISIOS','SP','11'),
('QUIXADA','CE','88'),
('IPIGUÁ','SP','17'),
('CACHOEIRA DE MINAS','MG','35'),
('MANHUAÇU','MG','33'),
('SERRA DOS SALITRES','MG','34'),
('CAPELINHA','MG','33'),
('OSVALDO CRUZ','SP','18'),
('Tremembé','SP','11'),
(' SAO JOSE DO VALE DO RIO','RJ','24'),
('SAO JOSE DO VALE DO RIO P','RJ','24'),
('MARTINOPOLIS','SP','18'),
('BAYEUX','PB','83'),
('Ponte Nova','MG','31'),
('TOME-ACU','PA','91'),
('MANACAS','MG','31'),
('IBIACA','RS','54'),
('Morro Reuter','RS','51'),
('NEROPOLIS','GO','62'),
('SANTA CRUZ RN','RN','84'),
('EUSEBIO','CE','85'),
('GARIBALDI','RS','54'),
('SAO JOAQUIM DE BICAS','MG','31'),
('CAJAMAR','SP','11'),
('MARACANAU','CE','85'),
('GUAÇUI','ES','28'),
('Tramanda?','RS','51');

-- ── Normaliza pontuação e prefixa DDD em clientes.telefone/whatsapp ────────────
-- Critério "já tem DDD": telefone com 10+ dígitos (depois de remover não-dígitos).
-- Critério "precisa de DDD": 8 dígitos (fixo) ou 9 dígitos (celular).

UPDATE clientes c
JOIN cidades_ddd_referencia r ON r.cidade = UPPER(c.cidade) AND r.uf = c.uf
SET c.telefone = CONCAT(
  '(', r.ddd, ') ',
  IF(
    LENGTH(REGEXP_REPLACE(c.telefone, '[^0-9]', '')) = 9,
    CONCAT(LEFT(REGEXP_REPLACE(c.telefone, '[^0-9]', ''), 5), '-', RIGHT(REGEXP_REPLACE(c.telefone, '[^0-9]', ''), 4)),
    CONCAT(LEFT(REGEXP_REPLACE(c.telefone, '[^0-9]', ''), 4), '-', RIGHT(REGEXP_REPLACE(c.telefone, '[^0-9]', ''), 4))
  )
)
WHERE c.telefone IS NOT NULL
  AND c.telefone <> ''
  AND LENGTH(REGEXP_REPLACE(c.telefone, '[^0-9]', '')) IN (8, 9);

-- Reformata quem já tem DDD embutido (10 ou 11 dígitos) para o padrão "(XX) XXXXX-XXXX"
UPDATE clientes c
SET c.telefone = CONCAT(
  '(', LEFT(REGEXP_REPLACE(c.telefone, '[^0-9]', ''), 2), ') ',
  IF(
    LENGTH(REGEXP_REPLACE(c.telefone, '[^0-9]', '')) = 11,
    CONCAT(SUBSTRING(REGEXP_REPLACE(c.telefone, '[^0-9]', ''), 3, 5), '-', RIGHT(REGEXP_REPLACE(c.telefone, '[^0-9]', ''), 4)),
    CONCAT(SUBSTRING(REGEXP_REPLACE(c.telefone, '[^0-9]', ''), 3, 4), '-', RIGHT(REGEXP_REPLACE(c.telefone, '[^0-9]', ''), 4))
  )
)
WHERE c.telefone IS NOT NULL
  AND c.telefone <> ''
  AND LENGTH(REGEXP_REPLACE(c.telefone, '[^0-9]', '')) IN (10, 11);

-- ── Mesma correção para clientes.whatsapp ──────────────────────────────────────
UPDATE clientes c
JOIN cidades_ddd_referencia r ON r.cidade = UPPER(c.cidade) AND r.uf = c.uf
SET c.whatsapp = CONCAT(
  '(', r.ddd, ') ',
  IF(
    LENGTH(REGEXP_REPLACE(c.whatsapp, '[^0-9]', '')) = 9,
    CONCAT(LEFT(REGEXP_REPLACE(c.whatsapp, '[^0-9]', ''), 5), '-', RIGHT(REGEXP_REPLACE(c.whatsapp, '[^0-9]', ''), 4)),
    CONCAT(LEFT(REGEXP_REPLACE(c.whatsapp, '[^0-9]', ''), 4), '-', RIGHT(REGEXP_REPLACE(c.whatsapp, '[^0-9]', ''), 4))
  )
)
WHERE c.whatsapp IS NOT NULL
  AND c.whatsapp <> ''
  AND LENGTH(REGEXP_REPLACE(c.whatsapp, '[^0-9]', '')) IN (8, 9);

UPDATE clientes c
SET c.whatsapp = CONCAT(
  '(', LEFT(REGEXP_REPLACE(c.whatsapp, '[^0-9]', ''), 2), ') ',
  IF(
    LENGTH(REGEXP_REPLACE(c.whatsapp, '[^0-9]', '')) = 11,
    CONCAT(SUBSTRING(REGEXP_REPLACE(c.whatsapp, '[^0-9]', ''), 3, 5), '-', RIGHT(REGEXP_REPLACE(c.whatsapp, '[^0-9]', ''), 4)),
    CONCAT(SUBSTRING(REGEXP_REPLACE(c.whatsapp, '[^0-9]', ''), 3, 4), '-', RIGHT(REGEXP_REPLACE(c.whatsapp, '[^0-9]', ''), 4))
  )
)
WHERE c.whatsapp IS NOT NULL
  AND c.whatsapp <> ''
  AND LENGTH(REGEXP_REPLACE(c.whatsapp, '[^0-9]', '')) IN (10, 11);

-- ── Mesma correção para contatos.telefone/celular/whatsapp (usa a cidade do cliente) ──
UPDATE contatos ct
JOIN clientes c ON c.id = ct.cliente_id
JOIN cidades_ddd_referencia r ON r.cidade = UPPER(c.cidade) AND r.uf = c.uf
SET ct.telefone = CONCAT(
  '(', r.ddd, ') ',
  CONCAT(LEFT(REGEXP_REPLACE(ct.telefone, '[^0-9]', ''), 4), '-', RIGHT(REGEXP_REPLACE(ct.telefone, '[^0-9]', ''), 4))
)
WHERE ct.telefone IS NOT NULL
  AND ct.telefone <> ''
  AND LENGTH(REGEXP_REPLACE(ct.telefone, '[^0-9]', '')) = 8;

UPDATE contatos ct
JOIN clientes c ON c.id = ct.cliente_id
JOIN cidades_ddd_referencia r ON r.cidade = UPPER(c.cidade) AND r.uf = c.uf
SET ct.celular = CONCAT(
  '(', r.ddd, ') ',
  CONCAT(LEFT(REGEXP_REPLACE(ct.celular, '[^0-9]', ''), 5), '-', RIGHT(REGEXP_REPLACE(ct.celular, '[^0-9]', ''), 4))
)
WHERE ct.celular IS NOT NULL
  AND ct.celular <> ''
  AND LENGTH(REGEXP_REPLACE(ct.celular, '[^0-9]', '')) = 9;

UPDATE contatos ct
JOIN clientes c ON c.id = ct.cliente_id
JOIN cidades_ddd_referencia r ON r.cidade = UPPER(c.cidade) AND r.uf = c.uf
SET ct.whatsapp = CONCAT(
  '(', r.ddd, ') ',
  IF(
    LENGTH(REGEXP_REPLACE(ct.whatsapp, '[^0-9]', '')) = 9,
    CONCAT(LEFT(REGEXP_REPLACE(ct.whatsapp, '[^0-9]', ''), 5), '-', RIGHT(REGEXP_REPLACE(ct.whatsapp, '[^0-9]', ''), 4)),
    CONCAT(LEFT(REGEXP_REPLACE(ct.whatsapp, '[^0-9]', ''), 4), '-', RIGHT(REGEXP_REPLACE(ct.whatsapp, '[^0-9]', ''), 4))
  )
)
WHERE ct.whatsapp IS NOT NULL
  AND ct.whatsapp <> ''
  AND LENGTH(REGEXP_REPLACE(ct.whatsapp, '[^0-9]', '')) IN (8, 9);

-- Tabela de referência era só uma muleta para esta correção pontual — descartada.
DROP TABLE IF EXISTS cidades_ddd_referencia;
